using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Time.Testing;

namespace Codex.Backend.Tests;

/// <summary>
/// FSRS golden-vector + cross-restart-persistence tests. Both drive the REAL review flow through
/// HTTP with a <see cref="FakeTimeProvider"/> wired through DI, so "now" (and therefore elapsed
/// days -> the whole schedule) is deterministic. Time is injected via TimeProvider (default
/// TimeProvider.System in production); tests swap in a fake and advance it explicitly.
/// </summary>
public sealed class FsrsFlowTests
{
    /// <summary>A factory whose TimeProvider is a caller-controlled FakeTimeProvider on a chosen DB file.</summary>
    private sealed class FakeClockFactory : WebApplicationFactory<Program>
    {
        private readonly string _dbPath;
        public FakeTimeProvider Clock { get; }

        public FakeClockFactory(string dbPath, DateTimeOffset start)
        {
            _dbPath = dbPath;
            Clock = new FakeTimeProvider(start);
        }

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureAppConfiguration(cfg => cfg.AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["Database:Path"] = _dbPath,
                ["Auth:DevMode"] = "true",
            }));
            // Replace the system clock with the fake one so the review/FSRS path is deterministic.
            builder.ConfigureServices(services =>
            {
                services.RemoveAll<TimeProvider>();
                services.AddSingleton<TimeProvider>(Clock);
            });
        }
    }

    private static async Task<JsonElement> Json(HttpResponseMessage r)
        => JsonDocument.Parse(await r.Content.ReadAsStringAsync()).RootElement;

    private static async Task<string> AuthToken(HttpClient client, long user)
    {
        var r = await client.PostAsJsonAsync("/api/auth", new { devUserId = user });
        r.EnsureSuccessStatusCode();
        return (await Json(r)).GetProperty("token").GetString()!;
    }

    private static HttpRequestMessage Bearer(HttpMethod m, string path, string token, object? body = null)
    {
        var msg = new HttpRequestMessage(m, path);
        msg.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        if (body is not null) msg.Content = JsonContent.Create(body);
        return msg;
    }

    /// <summary>
    /// One reference sequence and its py-fsrs-executed expected values.
    /// Intervals are in DAYS; S/D are the terminal memory state; State is the terminal lifecycle.
    /// </summary>
    /// <remarks>
    /// GROUND TRUTH: generated by running the REAL open-spaced-repetition/py-fsrs 6.3.1 default
    /// Scheduler (fuzzing OFF for determinism), reviewing each card exactly when due. See
    /// .spikes/rs-fsrs-align/reference.py and REFERENCE_OUTPUT.txt. Our FsrsScheduler is a faithful
    /// port and reproduces these numbers to the second / to 6 decimals of stability.
    /// </remarks>
    public sealed record GoldenCase(
        string Name, int[] Grades, double[] IntervalDays, double Stability, double Difficulty, string State);

    public static IEnumerable<object[]> GoldenCases()
    {
        // 60s = 0.0006944.. d, 600s = 0.0069444.. d, 330s = 0.0038194.. d
        const double D60 = 60.0 / 86400.0, D600 = 600.0 / 86400.0, D330 = 330.0 / 86400.0;
        yield return new object[] { new GoldenCase(
            "Again,Good,Good,Good,Good,Good", new[] { 1, 3, 3, 3, 3, 3 },
            new[] { D60, D600, 1.0, 2.0, 7.0, 19.0 }, 19.169023, 6.357487, "Review") };
        yield return new object[] { new GoldenCase(
            "Good,Good,Good", new[] { 3, 3, 3 },
            new[] { D600, 2.0, 11.0 }, 10.971048, 2.104331, "Review") };
        yield return new object[] { new GoldenCase(
            "Again,Again,Good", new[] { 1, 1, 3 },
            new[] { D60, D60, D600 }, 0.103141, 8.792727, "Learning") };
        yield return new object[] { new GoldenCase(
            "Hard,Good,Easy", new[] { 2, 3, 4 },
            new[] { D330, D600, 2.0 }, 2.369135, 3.450928, "Review") };
    }

    /// <summary>
    /// GOLDEN VECTOR — exact alignment to the REAL py-fsrs 6.3.1 default scheduler.
    ///
    /// Drives the production review flow over HTTP with a deterministic <see cref="FakeTimeProvider"/>,
    /// reviewing each card exactly when due (advance the clock by the previous interval), so the
    /// elapsed time — and therefore the whole schedule — reproduces py-fsrs's "review-when-due"
    /// cadence. Asserts the intervals, terminal stability/difficulty AND the terminal lifecycle state
    /// match the numbers executed by py-fsrs. Tolerance: 1e-4 on intervals (sub-second on the
    /// minute-scale learning steps), 1e-3 on S/D — well inside double round-trip through JSON.
    /// </summary>
    [Theory]
    [MemberData(nameof(GoldenCases))]
    public async Task GoldenVector_MatchesPyFsrs(GoldenCase gc)
    {
        string dbPath = Path.Combine(Path.GetTempPath(), $"codex-golden-{Guid.NewGuid():N}.db");
        var start = new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);
        using var factory = new FakeClockFactory(dbPath, start);
        var client = factory.CreateClient();
        long user = 42_000 + Random.Shared.Next(1, 500_000);
        const string item = "CS.S1.value-types-copy/c1";

        double lastInterval = 0;
        double stability = 0, difficulty = 0;
        string state = "";
        for (int i = 0; i < gc.Grades.Length; i++)
        {
            // Advance the clock by the previous card's exact interval, so we review exactly when due.
            if (i > 0) factory.Clock.Advance(TimeSpan.FromDays(lastInterval));

            // Re-auth each step: the schedule can span >7 days (longer than a token's lifetime) and
            // the session token expires on the SAME injected clock — so mint a fresh one at "now".
            string token = await AuthToken(client, user);
            var raw = await client.SendAsync(
                Bearer(HttpMethod.Post, "/api/review", token, new { itemId = item, grade = gc.Grades[i] }));
            string bodyStr = await raw.Content.ReadAsStringAsync();
            Assert.True(raw.IsSuccessStatusCode, $"[{gc.Name}] review {i} -> {(int)raw.StatusCode}: {bodyStr}");
            var res = JsonDocument.Parse(bodyStr).RootElement;

            double interval = res.GetProperty("intervalDays").GetDouble();
            stability = res.GetProperty("stability").GetDouble();
            difficulty = res.GetProperty("difficulty").GetDouble();
            state = res.GetProperty("state").GetString()!;
            Assert.InRange(interval, gc.IntervalDays[i] - 1e-4, gc.IntervalDays[i] + 1e-4);
            lastInterval = interval;
        }

        Assert.InRange(stability, gc.Stability - 1e-3, gc.Stability + 1e-3);
        Assert.InRange(difficulty, gc.Difficulty - 1e-3, gc.Difficulty + 1e-3);
        Assert.Equal(gc.State, state);
    }

    /// <summary>
    /// A wrong answer (Again) re-queues WITHIN the current session: the interval is a minute-scale
    /// learning step, far below any same-day threshold, so the card comes straight back for
    /// correction instead of ~5h (0.2 day) later as the old long-term-only scheduler produced.
    /// </summary>
    [Fact]
    public async Task Again_ReQueuesWithinSession_NotHoursLater()
    {
        string dbPath = Path.Combine(Path.GetTempPath(), $"codex-again-{Guid.NewGuid():N}.db");
        var start = new DateTimeOffset(2026, 2, 1, 0, 0, 0, TimeSpan.Zero);
        using var factory = new FakeClockFactory(dbPath, start);
        var client = factory.CreateClient();
        long user = 33_000 + Random.Shared.Next(1, 500_000);
        const string item = "CS.S1.value-types-copy/c1";

        string token = await AuthToken(client, user);
        var res = JsonDocument.Parse(await (await client.SendAsync(
            Bearer(HttpMethod.Post, "/api/review", token, new { itemId = item, grade = 1 })))
            .Content.ReadAsStringAsync()).RootElement;

        double intervalDays = res.GetProperty("intervalDays").GetDouble();
        Assert.Equal("Learning", res.GetProperty("state").GetString());
        // 1-minute learning step == 0.000694 d (the API rounds intervalDays to 4 dp -> 0.0007).
        // Assert it is far below even a 1-hour (0.0417 d) threshold — the card is due again this
        // session, not ~5h (0.2 d) later as the old long-term-only scheduler produced.
        Assert.True(intervalDays < 1.0 / 24.0,
            $"Again must re-queue within the hour, got {intervalDays:0.#####} d ({intervalDays * 24:0.##} h)");
        Assert.InRange(intervalDays, 60.0 / 86400.0 - 5e-5, 60.0 / 86400.0 + 5e-5);
    }

    /// <summary>
    /// PERSISTENCE ACROSS RESTART: review a card against a FILE-backed SQLite, dispose the factory,
    /// reopen the SAME file in a fresh factory with the clock advanced past due, and assert the
    /// schedule persisted — the card left the due queue at review time and comes back due on schedule.
    /// </summary>
    [Fact]
    public async Task Schedule_PersistsAcrossRestart_AndComesDueOnSchedule()
    {
        string dbPath = Path.Combine(Path.GetTempPath(), $"codex-persist-{Guid.NewGuid():N}.db");
        var start = new DateTimeOffset(2026, 3, 1, 0, 0, 0, TimeSpan.Zero);
        long user = 55_000 + Random.Shared.Next(1, 500_000);
        const string item = "CS.S1.value-types-copy/c1";
        double interval;

        // --- boot 1: review the card Good ---
        {
            using var factory = new FakeClockFactory(dbPath, start);
            var client = factory.CreateClient();
            string token = await AuthToken(client, user);

            var dueBefore = await Json(await client.SendAsync(Bearer(HttpMethod.Get, "/api/due", token)));
            Assert.Contains(dueBefore.GetProperty("items").EnumerateArray(),
                x => x.GetProperty("itemId").GetString() == item);

            var res = await Json(await client.SendAsync(
                Bearer(HttpMethod.Post, "/api/review", token, new { itemId = item, grade = 3 })));
            interval = res.GetProperty("intervalDays").GetDouble();
            // A brand-new Good is a learning step (600s == ~0.00694 d), still in the future.
            Assert.InRange(interval, 600.0 / 86400.0 - 1e-4, 600.0 / 86400.0 + 1e-4);

            // Immediately after review the card is NOT due.
            var dueAfter = await Json(await client.SendAsync(Bearer(HttpMethod.Get, "/api/due", token)));
            Assert.DoesNotContain(dueAfter.GetProperty("items").EnumerateArray(),
                x => x.GetProperty("itemId").GetString() == item);
        }

        // --- boot 2: SAME file, fresh factory, clock advanced PAST due ---
        {
            var later = start.AddDays(interval + 0.5); // half a day past due
            using var factory = new FakeClockFactory(dbPath, later);
            var client = factory.CreateClient();
            string token = await AuthToken(client, user);

            // The persisted review count survived the "restart".
            var prog = await Json(await client.SendAsync(Bearer(HttpMethod.Get, "/api/progress", token)));
            Assert.Equal(1, prog.GetProperty("reviewsTotal").GetInt32());
            Assert.Equal(1, prog.GetProperty("cards").GetProperty("seen").GetInt32());

            // With the clock past due, the SAME card is due again on schedule.
            var due = await Json(await client.SendAsync(Bearer(HttpMethod.Get, "/api/due", token)));
            Assert.Contains(due.GetProperty("items").EnumerateArray(),
                x => x.GetProperty("itemId").GetString() == item && !x.GetProperty("isNew").GetBoolean());
        }
    }
}
